# This file is maintained by Ansible

# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: casemix-pub-api
#app: your-app-name
#tenant: your-tenant-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  endpointType: EDGE
  runtime: dotnetcore3.1  
  region: ${env:AWS_DEFAULT_REGION}
  stage: ${env:ENV_NAME}
  logRetentionInDays: ${env:LOG_RETENTION}
  vpc:
    securityGroupIds:
      - ${env:SG_WEB}
    subnetIds:
      - ${env:PRIVATE_SUBNET_A}
      - ${env:PRIVATE_SUBNET_B}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DeleteNetworkInterface
      Resource: '*'
    - Effect: Allow
      Action:
        - "ses:SendRawEmail"
      Resource: "arn:aws:ses:${self:provider.region}:*:*"
    - Effect: Allow
      Action:
        - s3:*Object
        - s3:ListBucket
      Resource:
            - 'arn:aws:s3:::casemix-${env:ENV_NAME}-assets'
            - 'arn:aws:s3:::casemix-${env:ENV_NAME}-assets/*'
            - 'arn:aws:s3:::casemix-${env:ENV_NAME}-assets-secure'
            - 'arn:aws:s3:::casemix-${env:ENV_NAME}-assets-secure/*'
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'

package:
  individually: true

functions:
  api:
    handler: CaseMix.Web.Host::CaseMix.Web.Host.Startup.LambdaEntryPoint::FunctionHandlerAsync
    name: ${self:provider.stage}-casemix-pub-api
    description: Casemix Public Facing API, v1 POC+
    memorySize: 1024 
    timeout: 30 # max is 30s
    environment:
      ASPNETCORE_ENVIRONMENT: ${env:ENV_NAME}
    events:
      - http:
          path: /{proxy+}
          method: ANY
 
    # you can add packaging information here
    package:
      artifact: artifacts/backend.zip

plugins:
  - serverless-domain-manager
  - serverless-plugin-log-retention

custom:
  customDomain:
    domainName: api-casemix-${env:ENV_NAME}.${env:PUBLIC_DOMAIN}
    stage: ${env:ENV_NAME}
    basePath: ${env:ENV_NAME}
    # certificate name is first SAN listed
    certificateName: '*.${env:PUBLIC_DOMAIN}'
    createRoute53Record: true
    endpointType: 'EDGE'
    securityPolicy: tls_1_2

